### ISSUE TITLE
基础开发支持！

### ISSUE THREAD

**Issue by ysj52066** [liu-peiyu/SpringBootAdmin#24]
身边有不少java的新手都很喜欢这个项目，可能知识面没有那么广，也没那么多的框架的开发经验。所以很想借此项目来提高自己的眼界和能力。大家都有JAVA的基础，以及多多少少某些框架的使用经验。IDE使用也不尽相同。所以如果作者或者其他爱好者有时间的话，能否发布一份配置教程或者视频，能够让初学者很快搭建起来环境。  本项目如果能有一个交流的论坛或者社区、群就好了。
谢谢！！！

**Comment by liu-peiyu** [comment]
为方便大家讨论交流，请加QQ群：805442966
